# main-terraform-workflow.yml

name: Main Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment name'
        required: true
        default: 'test'

jobs:
  main_terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Reusable Terraform Workflow
      uses: Btejavn/new-az-terraform/.github/workflows/code.yml@main
      with:
        env: ${{ github.event.inputs.env }}
        path: 'src/terraform'
