
name: 'Terraform-Azure'

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment name'
        required: true
        default: 'test'
      path:
        description: 'Path to Terraform configurations'
        required: true
        default: 'src/terraform'

jobs:
  terraform_plan_and_deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      STAGE_NAME: ${{ inputs.env }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.path }}

    - name: Terraform Plan
      run: terraform plan 
      working-directory: ${{ inputs.path }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.path }}
